### ISSUE TITLE
POST- Body regex support

### ISSUE THREAD

**Issue by raDiesle** [gstroup/apimocker#2]
Sers,

a common use case for e.g. POST, PUT is to have e.g. json in the request body.
Within the request, an ID is given, which I want to return a concrete response to.

A simple regex would be enough, I think.

How do you think about such an improvement?

**Comment by dploeger** [comment]
@gstroup I'd like to reopen this to support my question in #33. I think, this would be the easiest way.

The switch-value would be enclosed with "/" to indicate, that it's a regexp and contains one regexp-group, that switch operates on.

**Comment by dploeger** [comment]
As I just saw in the code, the Switch itself is used to build up the filename. That will result in various problems when using regexp (I wonder, how the jsonpath-support even worked this way. :) ) So another feature would be to (optionally) specify a "description" about the switch.

**Comment by dploeger** [comment]
Proposal: an optional switch object like this:

```
switches: [
  "customerId", 
  {
    "type": "regexp",
    "switch": "/testreg([^p]*)p/",
    "key": "testregexppart"
  },
  {
    "type": "jsonpath",
    "switch": "$.car.engine.part",
    "key": "enginepart"
  }
]
```

Would result in files like "customerId1234.mock.json", "testregexppartex.mock.json" and "enginepartTiming%20Belt.json"

**Comment by raDiesle** [comment]
ya
