### ISSUE TITLE
'$' sign in URL is not working 

### ISSUE THREAD

**Issue by jawwadfarooq** [gstroup/apimocker#20]
Hi,

My service URL is like "abc/flights/$/incoming" and I am unable to mock this URL. Also there is no error in console.

Any workaround or solution.

Regards,

Jawwad

**Comment by gstroup** [comment]
This seems to be an issue with Express... I'll investigate further.

**Comment by jawwadfarooq** [comment]
Thanks! So finally have you fixed it?

**Comment by gstroup** [comment]
Sorry, but it's not fixed yet.  (My commit ENT was wrong, another issue is fixed.). I did take some time to look at this, but I haven't come up with a fix yet.

   -Greg

**Comment by eliasrmz** [comment]
I found same issue with URL using parenthesis. 
I tried escaping them just in case it was being parsed as a regex. Did not work.

Might it be related?

e.g. "segment01/segment02/entity(13040986)" 
returns a 404 not found.

Thanks!

**Comment by gstroup** [comment]
Cool, thanks for sharing the solution!  I learned something new.  I’ll add it to the readme.

**Comment by gstroup** [comment]
should be fixed now, by PR #83 .
