### ISSUE TITLE
Switches aren't working for :id on get

### ISSUE THREAD

**Issue by httpete** [gstroup/apimocker#27]
Hi,
I want to do a simple switch based on and id for example:

```javascript
"dogs/:id" { 
 "mockFile": "dogs/dog.json"
"verbs": [ "get"],
"switch": "id"
}
```

but it wont pick up dog1.dog.json with a request like:

GET /dogs/dog1

if I have it in the dogs directory. Thoughts? This is on the latest.

**Comment by ztsmith** [comment]
Try naming the file `id1.dog.json`

**Comment by httpete** [comment]
yep that's it. Worked! I just had to disable the quiet and it coughed up the goods.
