### ISSUE TITLE
Switch by json key

### ISSUE THREAD

**Issue by dploeger** [gstroup/apimocker#33]
I have the following request structure (all requests POST to /):

AuthRequest:
```
{
  "Header": {...},
  "Body": {
    "AuthRequest": { <Parameters for Auth Request> }
  }
}
```

GetMailboxRequest:
```
{
  "Header": {...},
  "Body": {
    "GetMailboxRequest": { <Parameters for GetMailbox Request> }
  }
}
```

I'd have to deliver two mocks. One for the AuthRequest and one for the GetMailboxRequest.

So I need to switch by the first key of "Body"? Is this possible? I don't see how I can configure this. JsonPath doesn't seem to work for this specific task.

**Comment by gstroup** [comment]
I believe this is fixed now, by your pull request.  Right?  If so, I will close this issue.  Thanks.

**Comment by dploeger** [comment]
Yes. I can work around this using the new regexp feature. Thanks.
