### ISSUE TITLE
Sample with SOAP request and swich SOAP response

### ISSUE THREAD

**Issue by javierpsf** [gstroup/apimocker#40]
Hi,

I can not find an example where the SOAP response change depending on what the SOAP request sent.
For example, if I send

`<code>es</code>`

I need receive (countryEs.xml)
`<country>Spain</country>`

and if I send
`<code>fr</code>`

I need receive (countryFr.xml)
`<country>France</country>`

could you help me with config.json?

Thank You!!!

**Comment by gstroup** [comment]
Right now, the switches don't work with XML request body parameters.  For now you could use a RegEx switch to check for a value in the XML.  In the future, we could probably add that feature.
