### ISSUE TITLE
Proxy post request hangs

### ISSUE THREAD

**Issue by oguzgu** [gstroup/apimocker#48]
With proxy request, posting with body hangs. You have to push bodyParser after proxy, this will fix the issue

**Comment by gstroup** [comment]
Just noticed this issue.  Sorry for the slowness.  I will take a look.

**Comment by pgraham** [comment]
I think that this is caused by this issue: https://github.com/villadora/express-http-proxy/issues/32

Updating to express-http-proxy 0.7.1 should fix this.
