### ISSUE TITLE
Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response

### ISSUE THREAD

**Issue by AshishPashap** [gstroup/apimocker#54]
Hi, 

We are facing an issue - XMLHttpRequest cannot load http://localhost:7879/myApp/myService/v1/account. Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.

I tried adding CORS module and also tried adding response headers in my mock server but it didn't work, later found that adding the PATCH in apimaker.js resolved the issue.

node_modules\apimocker\lib\apimocker.js should have res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,**PATCH**,DELETE'); instead res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');

Is there specific reason for not supporting PATCH ? without PATCH it works fine from postman but not working from our application.

It would be great if this could be resolved.

thanks,
Ashish Pashap

**Comment by ashishpashap** [comment]
I have tried adding custom header as suggested in document section - "Adding custom middleware" as below

        var customMiddleware = function(req, res, next) {
            res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,PATCH,DELETE');
            console.log("Set custom headers for "+req.method);
            next();
        };
        mocker= apimocker.createServer().setConfigFile("test/test-config.json");
        mocker.middlewares.unshift(customMiddleware);
        mocker.start();

Here are the console logs in executed order : 
log set in service.ts - "Set custom headers for OPTIONS"
log set in lib/apimocker.js - "apimaker.js overwriting custom headers for OPTIONS"

I believe calling/setting the custom headers should be in another way like first it should set from the lib/apimocker.js and if any custom header set then it should overwrite.

Please suggest me on the same.

**Comment by gstroup** [comment]
Fixed in version 0.4.12.

**Comment by AshishPashap** [comment]
wow.great, thanks a lot.

**Comment by thevjay** [comment]
Issue Description
I am facing a CORS error when making a PATCH request from my frontend (http://localhost:5173) to my backend (http://localhost:7777). The error states that PATCH is not allowed by Access-Control-Allow-Methods in the preflight response.

Error Message (Browser Console)

Access to fetch at 'http://localhost:7777/profile/edit' from origin 'http://localhost:5173' has been blocked by CORS policy: 
Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
