### ISSUE TITLE
different content-type values for different responses

### ISSUE THREAD

**Issue by tifferjames** [gstroup/apimocker#61]
It would be great if we could specify different headers for different responses. For example, I would like to return either a file or a json string, depending on the Accept header in the request.

I can use "switch" to send back a different response based on the Accept Header, but there doesn't seem to be any way to set the response headers (e.g. content-type, etc.) per response.

**Comment by tifferjames** [comment]
Perhaps an alternative solution might be to allow multiple configs for the same URL pattern. Each config would have to have a slightly different setup so that only one config entry matches the incoming request.

**Comment by tifferjames** [comment]
Sorry, my mistake, it looks like you can specify the "headers" within each response and/or switchResponse (though this feature isn't clear based on the documentation)

**Comment by gstroup** [comment]
You're right, that was not clear in the documentation.  I added an additional note.  The docs could probably use some more work.  If you have suggestions, let me know or make a pull request.  I'm closing this issue for now, but if it's still not clear, we can reopen.  Thanks!
