### ISSUE TITLE
support 404 by missing default mockFile

### ISSUE THREAD

**Issue by aburmeis** [gstroup/apimocker#65]
How to configure a mock that only returns a resource where the file is present for the switch but returns 404 otherwise? I would expect if I configure a mockFile test.json and have a switch id I would get id42.test.json contents if exists or 404 if test.json does not exists.

Even better would be to have an option to set the status for a missing mock file for a switch.

**Comment by aburmeis** [comment]
added a PR: https://github.com/gstroup/apimocker/pull/66

**Comment by apichick** [comment]
Could the PR be modified so we actually return the httpStatus code in responses/httpStatusCode and not only 404.

I think that owuld be achieved just changing 

res.send(404);

to

res.send(options.httpStatus);

Please let me know if that makes sense.

**Comment by gstroup** [comment]
Fixed in v0.4.16.  Thanks for the PR!
