### ISSUE TITLE
Provide support for optional basepath in URL

### ISSUE THREAD

**Issue by kurtkanaskie** [gstroup/apimocker#67]
I would like to be able to specify a "basepath" which is basically a prefix on webservices.

That helps me to use apimocker locally and in my Apigee API proxy, which specifies its own "basepath".

GET http://localhost:4000/basepath/customers

Then I can just change the value of basepath to "" when I deploy into Apigee
GET http://api-gateway:9000/basepath/customers

This can be done with express pretty straightforward.

apiMocker.express.use(options.basePath,apiMocker.router);

**Comment by gstroup** [comment]
Sounds like a reasonable change.  I'll try to add that in soon.  Also, pull requests are welcome!  If you make PR, please include a test or two.

**Comment by gstroup** [comment]
Fixed in v0.4.16.

**Comment by kurtkanaskie** [comment]
Works like a charm!

Thanks
