### ISSUE TITLE
Support Parse Server mocking.

### ISSUE THREAD

**Issue by ipuiu** [gstroup/apimocker#77]
Hi there.

Would be nice if this would also support Parse Server mocking.

The reason why it doesn't right now is that Parse Server avoids pre-flight requests by always sending a `Content-Type` of `text/plain` on the request headers.
Using that kind of `Content-Type` for requests that have the parameters inside the body as json makes the `switch` feature of apimocker useless - since that is not parsed in the current version with `body-parser`.
I would like to propose to add another middleware that will look something like this:

```
apiMocker.middlewares.push(bodyParser.json({
		strict: false,
		verify: saveBody,
		type: 'text/plain'
	}));
```
I will add it myself and make a PR but want to know how you feel about this.

**Comment by gstroup** [comment]
Thanks for the PR!  I haven't used the Parse API with content-type of text/plain.  Your proposal makes sense, I'm just a little concerned that the additional middleware might interfere with other requests that are not targeting the Parse API.  What do you think?  I see all the tests are passing, so we _should_ be OK.  Could you add a test for this new case, exercising your new middleware?

**Comment by ipuiu** [comment]
Hi @gstroup !

I will add a test for this case and I will try to improve a little the logic.
To be honest your concern seem very real to me also.
I'm thinking right now to add a boolean option also in the config that will enable or disable this extra middleware. This way only users that desire to mock Parse Server would enable it, therefore the others should be unaffected.
Thoughts ?
P.S. I've been using the modified version (forked) to do all e2e tests so far and it works fine.

**Comment by ipuiu** [comment]
Hi @gstroup !

I've did some changes to the PR.
By adding the new functionality as a option which by default is disabled I think the concern is removed.
I've also added some minor tests for the configuration.
Do you think we would need more tests for it ?
