### ISSUE TITLE
"TypeError: jsonPath.eval is not a function" is thrown when `JSONPath` is not installed. 

### ISSUE THREAD

**Issue by twalker** [gstroup/apimocker#97]
The [JSONPath](https://www.npmjs.com/package/JSONPath) dependency is not consistently installed with npm version v5+
It intermittently installs correctly, often on the 2nd attempt to `npm install` in a project dependent on `apimocker`. There appears to be a known issue with JSONPath and npm:
> (This package is being moved to "jsonpath-plus" to avoid npm problems in dealing with upper-case packages.)

When JSONPath is not installed during the install of apimocker, requests to apimocker throw a "TypeError: jsonPath.eval is not a function". In addition to JSONPath not installing consistently, the `JSONPath.eval` method used by apimocker has been deprecated.

### To reproduce
1. npm install
2. npm test

_Actual results:_
"JSONPath.eval is not a function" errors are thrown and cause the tests to fail.
If the error does not occur, try re-installing and run the tests again:
```
rm -rf node_modules
npm install
npm test
```

_Expected results:_
Tests to pass consistently after every `npm install`

**Comment by gstroup** [comment]
fixed in v1.0.4
